> ## **Assignment - Numpy Array Operations** 
>
> The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ai/learn/zero-to-data-analyst-bootcamp/assignment/assignment-4-exploring-numpy-functions
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and with the course community.
> 5. (Optional) Check out the notebooks shared by other participants and give feedback & appreciation.
>
> Try to give pick a theme for your assignment and give your notebook an interesting title e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this cell containing explanations before submitting or sharing your notebook online - to make it more presentable.




# Frequently Used NumPy Functions in Machine Learning & Data Science


**What is NumPy?**
* NumPy stands for Numerical Python, a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

**Why NumPy?**
* In Python we have lists that serve the purpose of arrays,but the are slow to process. NumpPy provide an array object that is up to 50X faster than traditional Python lists.

**How NumPy is faster than Lists?**
* NumPy arrays are stored at one continuous place in memory unlike in lists, so processes can access and manipulate them very efficiently, This behavior is called Locality of Reference in computer science.

In [217]:
!pip install jovian --upgrade -q

In [218]:
import jovian

In [ ]:
jovian.commit(project='zerotoanalyst-numpy-array-operations')

<IPython.core.display.Javascript object>

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [220]:
import numpy as np

### Creating a NumPy array

It is a normal Python list

In [221]:
array = [1,2,6,5,3,3,6,78,98]
array

[1, 2, 6, 5, 3, 3, 6, 78, 98]

Use `np.array()` to create a NumPy array

In [222]:
np_array = np.array([2,3,5,6,7,76,5,4,32])
np_array

array([ 2,  3,  5,  6,  7, 76,  5,  4, 32])

Lets try to create a random array with specified size and shape

In [223]:
random_array = np.random.randint(10, size=(5,3))
random_array

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

In the random array above, it will generate a new random array every time you execute the cell.So, lets use `random.seed()` to generated a unique random array every time we execute.

In [224]:
np.random.seed(3)
random_ar_1 = np.random.randint(20, size=(3,5))
random_ar_1

array([[10,  3,  8,  0, 19],
       [10, 11,  9, 10,  6],
       [ 0, 12,  7, 14, 17]])

In [225]:
np.random.seed(seed=0)
random_ar_2 = np.random.randint(20, size=(5,3))
random_ar_2

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [226]:
np.random.seed(1)
random_ar_3 = np.random.randint(20, size=(2,3,4))
random_ar_3

array([[[ 5, 11, 12,  8],
        [ 9, 11,  5, 15],
        [ 0, 16,  1, 12]],

       [[ 7, 13,  6, 18],
        [ 5, 18, 11, 10],
        [14, 18,  4,  9]]])

If we manually assign `seed=None` it will generate random arrays every time it executes

## Function 1 - Arithmetic Operation

***Example 1 - Arithmetic operation*** are basic mathematical functions used in arrays, Here we can add, subtract, multiply and divide


In [227]:
a1 = np.array([2, 5, 6])
a1

array([2, 5, 6])

In [228]:
a2 = np.array([[3, 7, 9.6],
              [7, 4, 8.8]])
a2

array([[3. , 7. , 9.6],
       [7. , 4. , 8.8]])

In [229]:
a1 + a2

array([[ 5. , 12. , 15.6],
       [ 9. ,  9. , 14.8]])

In [230]:
a1 - a2

array([[-1. , -2. , -3.6],
       [-5. ,  1. , -2.8]])

In [231]:
a3 = np.array([[4,7,9],
             [9,3,2.4]])
a3

array([[4. , 7. , 9. ],
       [9. , 3. , 2.4]])

In [232]:
a2 * a1

array([[ 6. , 35. , 57.6],
       [14. , 20. , 52.8]])

***Example 2*** 
- If we divide 2 arrays result will be a float value
- If we check for modulas 

In [233]:
a3 / a1

array([[2. , 1.4, 1.5],
       [4.5, 0.6, 0.4]])

In [234]:
a3 // a1

array([[2., 1., 1.],
       [4., 0., 0.]])

In [235]:
a1 ** 3

array([  8, 125, 216])

In [236]:
a2

array([[3. , 7. , 9.6],
       [7. , 4. , 8.8]])

In [237]:
a2 % a1

array([[1. , 2. , 3.6],
       [1. , 4. , 2.8]])

## Funtcion 2 - Aggregation
***Example 1 -***  Aggregation = Performing same operation on a number of things 


In [238]:
a1

array([2, 5, 6])

In [239]:
sum(a1)

13

In [240]:
np.sum(a1)

13

In [241]:
a2

array([[3. , 7. , 9.6],
       [7. , 4. , 8.8]])

In [242]:
np.mean(a2)

6.566666666666667

In [243]:
np.max(a2)

9.6

In [244]:
np.min(a2)

3.0

***Example 2*** 

In [245]:
# Standard deviaiton = a measure of how spread out a group of numbers is from the mean 
np.std(a2)

2.376037784959565

5.645555555555556

In [247]:
high_var_array = np.array([1, 10, 100, 200, 4000, 5000])
low_var_array = np.array([2,4,6,8,10,12])

In [248]:
np.var(high_var_array), np.var(low_var_array)

(4433496.805555556, 11.666666666666666)

***Example 3***

In [295]:
# Variance = the measure of average degree to which each number is different to the mean
# Higher variance = higher range of numbers
# Lower variance = lower range of numbers

np.var(a2)

5.645555555555556

In [249]:
np.std(high_var_array), np.std(low_var_array)

(2105.5870453523303, 3.415650255319866)

In [250]:
np.mean(high_var_array), np.mean(low_var_array)

(1551.8333333333333, 7.0)

## Function 3 - Reshape & Transpose



***Example 1 - Reshape***

In [251]:
a2

array([[3. , 7. , 9.6],
       [7. , 4. , 8.8]])

In [252]:
a2.shape

(2, 3)

In [253]:
random_ar_3

array([[[ 5, 11, 12,  8],
        [ 9, 11,  5, 15],
        [ 0, 16,  1, 12]],

       [[ 7, 13,  6, 18],
        [ 5, 18, 11, 10],
        [14, 18,  4,  9]]])

In [254]:
random_ar_3.shape

(2, 3, 4)

In [255]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[3. ],
        [7. ],
        [9.6]],

       [[7. ],
        [4. ],
        [8.8]]])

In [256]:
a2_reshape * random_ar_3

array([[[ 15. ,  33. ,  36. ,  24. ],
        [ 63. ,  77. ,  35. , 105. ],
        [  0. , 153.6,   9.6, 115.2]],

       [[ 49. ,  91. ,  42. , 126. ],
        [ 20. ,  72. ,  44. ,  40. ],
        [123.2, 158.4,  35.2,  79.2]]])

***Example 2 - Transpose***

In [257]:
a2

array([[3. , 7. , 9.6],
       [7. , 4. , 8.8]])

In [258]:
a2.shape

(2, 3)

In [259]:
a2.T

array([[3. , 7. ],
       [7. , 4. ],
       [9.6, 8.8]])

In [260]:
a2.T.shape

(3, 2)

In [261]:
random_ar_3

array([[[ 5, 11, 12,  8],
        [ 9, 11,  5, 15],
        [ 0, 16,  1, 12]],

       [[ 7, 13,  6, 18],
        [ 5, 18, 11, 10],
        [14, 18,  4,  9]]])

In [262]:
random_ar_3.shape

(2, 3, 4)

In [263]:
random_ar_3.T

array([[[ 5,  7],
        [ 9,  5],
        [ 0, 14]],

       [[11, 13],
        [11, 18],
        [16, 18]],

       [[12,  6],
        [ 5, 11],
        [ 1,  4]],

       [[ 8, 18],
        [15, 10],
        [12,  9]]])

In [264]:
random_ar_3.T.shape

(4, 3, 2)

## Function 4 - Linear Algebra

In [265]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [266]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [267]:
# np.dot(mat1, mat2)

In [268]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Function 5 - Comparision Operators

In [269]:
a1

array([2, 5, 6])

In [270]:
a2

array([[3. , 7. , 9.6],
       [7. , 4. , 8.8]])

In [271]:
a1 > a2

array([[False, False, False],
       [False,  True, False]])

In [272]:
a1 >= a2

array([[False, False, False],
       [False,  True, False]])

In [273]:
a1 == a2

array([[False, False, False],
       [False, False, False]])

In [274]:
a1 != a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [275]:
a1 > 5

array([False, False,  True])

In [276]:
bool_array = a2 < 7
bool_array

array([[ True, False, False],
       [False,  True, False]])

In [277]:
bool_array.dtype

dtype('bool')

## Function 6 - Sorting Operation

### Sort using `np.sort()`

In [278]:
random_ar_1

array([[10,  3,  8,  0, 19],
       [10, 11,  9, 10,  6],
       [ 0, 12,  7, 14, 17]])

In [279]:
np.sort(random_ar_1)

array([[ 0,  3,  8, 10, 19],
       [ 6,  9, 10, 10, 11],
       [ 0,  7, 12, 14, 17]])

In [280]:
random_ar_2

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [281]:
np.msort(random_ar_2)

array([[ 1,  3,  0],
       [ 3,  6,  7],
       [ 4,  6,  7],
       [ 9, 15, 12],
       [12, 19, 18]])

### argsort `np.argsort()`

In [282]:
sort_arr = np.array([9,53,16,387,125,678])
sort_arr

array([  9,  53,  16, 387, 125, 678])

In [283]:
np.argsort(sort_arr)

array([0, 2, 1, 4, 3, 5])

In [284]:
np.argmax(sort_arr)

5

In [285]:
np.argmin(sort_arr)

0

In [286]:
random_ar_1

array([[10,  3,  8,  0, 19],
       [10, 11,  9, 10,  6],
       [ 0, 12,  7, 14, 17]])

In [287]:
np.argsort(random_ar_1)

array([[3, 1, 2, 0, 4],
       [4, 2, 0, 3, 1],
       [0, 2, 1, 3, 4]])

In [288]:
np.argsort(random_ar_1, axis=0)

array([[2, 0, 2, 0, 1],
       [0, 1, 0, 1, 2],
       [1, 2, 1, 2, 0]])

In [289]:
np.argsort(random_ar_1, axis=1)

array([[3, 1, 2, 0, 4],
       [4, 2, 0, 3, 1],
       [0, 2, 1, 3, 4]])

In [290]:
np.argmax(random_ar_1)

4

In [291]:
np.argmax(random_ar_1, axis=0)

array([0, 2, 1, 2, 0])

In [292]:
np.argmax(random_ar_1, axis=1)

array([4, 1, 4])

In [293]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "trineshnk/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/trineshnk/numpy-array-operations


'https://jovian.ai/trineshnk/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [294]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "trineshnk/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/trineshnk/numpy-array-operations


'https://jovian.ai/trineshnk/numpy-array-operations'